# Generated by Django 5.2.17 on 2026-09-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name submitted by the prospective property owner.', max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(db_index=True, max_length=30, verbose_name='Phone Number')),
                ('eligibility_result', models.CharField(choices=[('Potentially Eligible', 'Potentially Eligible'), ('Needs Further Review', 'Needs Further Review'), ('Currently Unlikely to Qualify', 'Currently Unlikely to Qualify')], db_index=True, default='Needs Further Review', max_length=60, verbose_name='Eligibility Result')),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Raw responses to the 7 eligibility questions.', verbose_name='Questionnaire Answers')),
                ('email_sent', models.BooleanField(db_index=True, default=False, verbose_name='Email Sent')),
                ('email_error', models.TextField(blank=True, default='', verbose_name='Email Error Log')),
                ('whatsapp_sent', models.BooleanField(db_index=True, default=False, verbose_name='WhatsApp Sent')),
                ('whatsapp_error', models.TextField(blank=True, default='', verbose_name='WhatsApp Error Log')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='lead_created_desc_idx'), models.Index(fields=['eligibility_result'], name='lead_eligibility_idx'), models.Index(fields=['email'], name='lead_email_idx')],
            },
        ),
    ]
