"""
Email notification service using Resend API.
Provides structured dispatch, formatting, and safe development fallback.
"""

import logging
from typing import Any, Dict
from django.conf import settings
import requests
from calculator.eligibility import QUESTION_MAP

logger = logging.getLogger(__name__)


def build_email_content(lead: Any) -> Dict[str, str]:
    """
    Builds both plaintext and HTML representations of the lead notification email.
    """
    timestamp_str = (
        lead.created_at.strftime("%Y-%m-%d %H:%M:%S UTC")
        if lead.created_at
        else "Just now"
    )

    # Format answers
    answers_text = []
    answers_html = []
    for q_id, is_yes in (lead.answers or {}).items():
        question_text = QUESTION_MAP.get(q_id, {}).get("text", q_id)
        answer_str = "Yes" if is_yes else "No"
        answers_text.append(f"  - {question_text}: {answer_str}")
        answers_html.append(
            f"<tr><td style='padding: 6px 12px; border-bottom: 1px solid #e2e8f0;'><strong>{question_text}</strong></td>"
            f"<td style='padding: 6px 12px; border-bottom: 1px solid #e2e8f0; color: {'#166534' if is_yes else '#991b1b'};'><strong>{answer_str}</strong></td></tr>"
        )

    answers_text_block = "\n".join(answers_text) or "  (No question data provided)"
    answers_html_block = "".join(answers_html) or "<tr><td colspan='2'>No question data</td></tr>"

    subject = f"New ADU Lead: {lead.name} ({lead.eligibility_result})"

    plain_text = f"""
==================================================
NEW ADU ELIGIBILITY LEAD
==================================================

CONTACT INFORMATION:
- Name:  {lead.name}
- Email: {lead.email}
- Phone: {lead.phone}

EVALUATION RESULT:
- Status: {lead.eligibility_result}
- Time:   {timestamp_str}

QUESTIONNAIRE RESPONSES:
{answers_text_block}

--------------------------------------------------
Lead ID: #{lead.id}
Generated by ADU Eligibility Calculator
==================================================
""".strip()

    html_content = f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{subject}</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f8fafc; margin: 0; padding: 24px; color: #1e293b;">
  <div style="max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 8px; overflow: hidden; border: 1px solid #e2e8f0; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
    <div style="background-color: #0f172a; padding: 20px; color: #ffffff;">
      <h2 style="margin: 0; font-size: 20px;">New ADU Eligibility Lead</h2>
      <p style="margin: 4px 0 0 0; font-size: 14px; color: #94a3b8;">Captured from public assessment tool</p>
    </div>
    
    <div style="padding: 24px;">
      <h3 style="font-size: 16px; margin-top: 0; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;">Prospect Details</h3>
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 14px;">
        <tr><td style="padding: 6px 0; color: #64748b; width: 120px;">Full Name:</td><td><strong>{lead.name}</strong></td></tr>
        <tr><td style="padding: 6px 0; color: #64748b;">Email:</td><td><a href="mailto:{lead.email}" style="color: #2563eb;">{lead.email}</a></td></tr>
        <tr><td style="padding: 6px 0; color: #64748b;">Phone:</td><td><a href="tel:{lead.phone}" style="color: #2563eb;">{lead.phone}</a></td></tr>
        <tr><td style="padding: 6px 0; color: #64748b;">Eligibility Result:</td><td><span style="background: #e0f2fe; color: #0369a1; padding: 3px 8px; border-radius: 4px; font-weight: bold;">{lead.eligibility_result}</span></td></tr>
        <tr><td style="padding: 6px 0; color: #64748b;">Submitted At:</td><td>{timestamp_str}</td></tr>
      </table>

      <h3 style="font-size: 16px; margin-top: 24px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;">Questionnaire Responses</h3>
      <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
        <thead>
          <tr style="background: #f1f5f9; text-align: left;">
            <th style="padding: 8px 12px;">Question</th>
            <th style="padding: 8px 12px;">Answer</th>
          </tr>
        </thead>
        <tbody>
          {answers_html_block}
        </tbody>
      </table>
    </div>

    <div style="background-color: #f8fafc; padding: 16px 24px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b; text-align: center;">
      Lead ID #{lead.id} &bull; ADU Advisor Prototype
    </div>
  </div>
</body>
</html>
"""

    return {
        "subject": subject,
        "text": plain_text,
        "html": html_content,
    }


def send_lead_email_notification(lead: Any) -> Dict[str, Any]:
    """
    Sends email notification via Resend API or logs mock output if API key is not configured.
    Returns a structured dictionary:
    {
        "success": bool,
        "simulated": bool,
        "message_id": Optional[str],
        "error": Optional[str],
    }
    """
    api_key = getattr(settings, "RESEND_API_KEY", "").strip()
    from_email = getattr(settings, "DEFAULT_FROM_EMAIL", "onboarding@resend.dev")
    to_email = getattr(settings, "LEAD_NOTIFICATION_EMAIL", "admin@example.com")

    content = build_email_content(lead)

    # Safe development fallback
    if not api_key:
        logger.info(
            "[EMAIL SERVICE] RESEND_API_KEY not configured. Email dispatch skipped/mocked for Lead #%s (%s).",
            lead.id,
            lead.email,
        )
        return {
            "success": False,
            "simulated": True,
            "message_id": None,
            "error": "RESEND_API_KEY is not configured (simulated in development).",
        }

    # Live delivery via Resend HTTP API
    endpoint = "https://api.resend.com/emails"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "User-Agent": "ADU-Eligibility-Calculator/1.0",
    }
    payload = {
        "from": from_email,
        "to": [to_email],
        "subject": content["subject"],
        "text": content["text"],
        "html": content["html"],
    }

    try:
        response = requests.post(endpoint, json=payload, headers=headers, timeout=10)
        if response.status_code in (200, 201):
            data = response.json()
            msg_id = data.get("id", "resend_ok")
            logger.info("Email notification successfully sent for Lead #%s via Resend (ID: %s)", lead.id, msg_id)
            return {
                "success": True,
                "simulated": False,
                "message_id": msg_id,
                "error": None,
            }
        else:
            err_msg = f"Resend API error (HTTP {response.status_code}): {response.text}"
            logger.error("Failed to send email for Lead #%s: %s", lead.id, err_msg)
            return {
                "success": False,
                "simulated": False,
                "message_id": None,
                "error": err_msg,
            }
    except requests.RequestException as exc:
        err_msg = f"Network exception connecting to Resend: {str(exc)}"
        logger.error("Exception sending email for Lead #%s: %s", lead.id, err_msg)
        return {
            "success": False,
            "simulated": False,
            "message_id": None,
            "error": err_msg,
        }
